# Generated by Django 3.2.8 on 2021-10-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211012_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='product',
            new_name='product_id',
        ),
    ]
